---
name: Docker Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker and Docker Compose
        run: |
          echo "Installing Docker Compose..."
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Check Docker Version
        run: docker --version

      - name: Check Docker Service
        run: |
          echo "Checking Docker service status..."
          sudo systemctl start docker
          sudo systemctl status docker
          docker info

      - name: Create docker-compose.yml
        run: |
          echo "version: '3.3'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  app:" >> docker-compose.yml
          echo "    build:" >> docker-compose.yml
          echo "      context: ." >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '8000:8000'" >> docker-compose.yml
          echo "    volumes:" >> docker-compose.yml
          echo "      - ./app:/app" >> docker-compose.yml
          echo "    command: sh -c 'python manage.py test'" >> docker-compose.yml

      - name: Run Tests
        run: docker-compose run --rm app
